kind = "web"
previewPath = "/"
title = "NJIRLAH AI"
version = "1.0.0"
id = "artifacts/njirlah-ai"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22978

[services.development]
run = "pnpm --filter @workspace/njirlah-ai run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/njirlah-ai", "run", "build" ]
publicDir = "artifacts/njirlah-ai/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22978"
BASE_PATH = "/"
